name: Tests

on:
  pull_request:

jobs:
  can-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the container image
        run: docker build .